#!/usr/bin/env node

const yargs = require('yargs');

yargs
  .commandDir('cmds')
  .demandCommand()
  .option('host', {
    describe: 'redis host',
    global: true,
    required: true,
    default: 'localhost'
  })
  .option('port', {
    describe: 'redis port',
    global: true,
    required: true,
    default: 6379
  })
  .option('db', {
    describe: 'redis db index',
    global: true,
    required: true,
    default: 0
  })
  .help()
  .argv

// cfg.redis = {
//   host: 'localhost',
//   port: '6379',
//   db: 0
// };